---
title: "The Power of Efficiency"
format: html
editor: visual
---

As we've said in the class efficiency is a pivotal component of statistical computing (and data science). In this essay, give an explanation of what that term "efficiency" means in relation to statistical computing and describe some places where you encountered efficiency and understood its importance. Your essay should address the following questions:

-   What is the definition of "efficiency"?

-   What does efficiency look like in statistical computing / data science?

-   What does efficiency allow you to do?

-   Why is efficiency important?

-   Where did you encounter efficiency, and what were some ["a-ha" moments](https://www.merriam-webster.com/dictionary/aha%20moment) you had about efficiency? (For the latter, tie each a-ha moment to an artifact in the portfolio.)

Efficiency means achieving maximum productivity with minimum wasted effort or expense. In statistical computing sense, this means your code is written in a way that completes the objective in a way that minimizing computing times. Efficient code should you to reproduce and scale your code more easily. Efficiency especially important when working with larger data sets due to it being scaled easily. This makes working with these data sets managble as there are often hundreds of thousands of entries in these data sets. One "a-ha" moment I had came from using the filter() function. The ability to filter multiple variables at the same time made me really thing about how to maximize efficiency. My code for pe-1-one-call demonstrates what I am talking about.
